services:
  db:
    image: postgres:17.5-alpine
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - fastapi-app-network

  app:
    image: fastapi-app
    container_name: fastapi-app
    ports:
      - 8000:8000
    # volumes:
    #   - .:/home
    depends_on:
      - db
    networks:
      - fastapi-app-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

networks:
  fastapi-app-network:
