"""added date_formed field to Department

Revision ID: 7729b24fc03b
Revises: c2264c57d77a
Create Date: 2025-05-26 17:29:49.520006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7729b24fc03b'
down_revision: Union[str, None] = 'c2264c57d77a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('date_formed', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('department', 'date_formed')
    # ### end Alembic commands ###
